"$schema" = 'https://starship.rs/config-schema.json'

# Insert a blank line between shell prompts
add_newline = true

# Increase the default command timeout to 2 seconds
command_timeout = 2000
scan_timeout = 10

# The overall prompt format, in order of appearance
# Each segment can be individually configured below
format = """
[â–‘â–’â–“â–ˆ](red)\
$os\
$username\
[â–’](bg:peach fg:red)\
$directory\
[â–’](bg:yellow fg:peach)\
$git_branch\
$git_status\
$git_commit\
$git_metrics\
$git_state\
${custom.git_config_email}\
[â–’](fg:yellow bg:green)\
$bun\
$c\
$cobol\
$cpp\
$crystal\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$gradle\
$haskell\
$haxe\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$odin\
$perl\
$php\
$purescript\
$python\
$quarto\
$raku\
$red\
$rlang\
$ruby\
$rust\
$scala\
$swift\
$typst\
$vlang\
$zig\
[â–’](fg:green bg:sapphire)\
$cmake\
$conda\
$docker_context\
$helm\
$kubernetes\
$package\
$terraform\
[â–’](fg:sapphire bg:lavender)\
$time\
$cmd_duration\
$battery\
[â–ˆâ–“â–’â–‘](lavender)\
$line_break\
$character
"""

# Use the Catppuccin Mocha color palette
palette = "catppuccin_mocha"

# Fill character (empty space) between modules, if needed
[fill]
symbol = " "

# Disable the line break between the first and second prompt lines
[line_break]
disabled = false


# --- unused modules ---

# [env_var]
# [hostname]
# [jobs]
# [localip]
# [memory_usage]
# [mise]
# [pixi]
# [shell]
# [shlvl]
# [status]
# [sudo]
# [vcsh]


# --- Basic Modules ---

# You can also replace your username with a neat symbol like ï„  or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:red fg:crust"
style_root = "bg:red fg:crust"
format = "[ $user ]($style)"
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
disabled = false
style = "bg:red fg:crust"

[os.symbols]
Windows = "îœ"
Ubuntu = "ó°•ˆ"
SUSE = "ïŒ”"
Raspbian = "ó°¿"
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Android = "îœ"
Arch = "ó°£‡"
Debian = "ó°£š"

# Customize the format of the working directory
[directory]
truncate_to_repo = true
truncation_length = 3
truncation_symbol = "â€¦/"
format = "[ $path ]($style)"
style = "bg:peach fg:crust"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ó°ˆ™"
"Downloads" = "ï€™"
"Music" = "ó°š"
"Pictures" = "ï€¾"
"Repos" = "ó°²‹"
# Keep in mind that the order matters. For example:
# "Important Documents" = " ó°ˆ™ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ó°ˆ™ " = " ó°ˆ™ï„ª "



# --- Git Modules ---

[git_branch]
symbol = "ï˜"
style = "bg:yellow"
format = "[[ $symbol $branch(:$remote_branch) ](fg:crust bg:yellow)]($style)"

[git_status]
style = "bg:yellow"
format = "[[($all_status$ahead_behind)](fg:crust bg:yellow)]($style)"

[git_commit]
style = "bg:yellow"
format = "[[(($hash$tag)](fg:crust bg:yellow)]($style)"
disabled = true

[git_metrics]
format = "([+$added]($added_style)) ([-$deleted]($deleted_style))"
added_style = "bold bg:yellow fg:green"
deleted_style = "bold bg:yellow fg:red"
disabled = true

[git_state]
style = "bg:yellow"
format = "[[ $state( $progress_current/$progress_total)](fg:crust bg:yellow)]($style)"
disabled = true



# --- Custom Modules ---

# Output the current git config email address
[custom.git_config_email]
description = "Output the current git user's configured email address."
command = "git config user.email"
format = "[$symbol( îœ‰ $output) ]($style)"
# Only when inside git repository
when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"
style = "bg:yellow fg:crust"



# --- Language & Runtime Version Modules ---

[bun]
symbol = "î¯"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[c]
symbol = "î˜"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[cobol]
symbol = "âš™ï¸"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[cpp]
symbol = "î˜"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[crystal]
symbol = "î˜¯"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[dart]
symbol = "î˜"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[deno]
symbol = "îŸ€"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[dotnet]
symbol = "îŸ†"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[elixir]
symbol = "î‰µ"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[elm]
symbol = "î˜¬"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[erlang]
symbol = "î±"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[fennel]
symbol = "îš¯"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[gleam]
symbol = "ó°¦¥"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[golang]
symbol = "ó°Ÿ“"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[gradle]
symbol = "îŸ²"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[haskell]
symbol = "î˜Ÿ"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[haxe]
symbol = "îŸº"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[java]
symbol = "î‰–"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[julia]
symbol = "î˜¤"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[kotlin]
symbol = "î˜´"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[lua]
symbol = "ó°¢±"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[nim]
symbol = "ó°†¥"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[nodejs]
symbol = "îœ˜"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[ocaml]
symbol = "î¡"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[odin]
symbol = "Ã˜"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[perl]
symbol = "î©"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[php]
symbol = "î˜ˆ"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[purescript]
symbol = "î˜°"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[python]
symbol = "î˜†"
style = "bg:green"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:crust bg:green)]($style)'

[quarto]
symbol = "î"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[raku]
symbol = "îŠ"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[red]
symbol = "ó±¥’"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[rlang]
symbol = "î¢"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[ruby]
symbol = "î‘"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[rust]
symbol = "î¨"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[scala]
symbol = "îœ·"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[swift]
symbol = "î•"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[typst]
symbol = "ï¿"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[vlang]
symbol = "îš¬"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"

[zig]
symbol = "î£¯"
style = "bg:green"
format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)"


# --- Other Useful Modules ---

[cmake]
disabled = false
symbol = "î”"
style = "fg:crust bg:sapphire"
format = "[[ $symbol$version ](fg:crust bg:sapphire)]($style)"

[conda]
symbol = "ï„Œ"
style = "fg:crust bg:sapphire"
format = "[[ $symbol$environment ](fg:crust bg:sapphire)]($style)"
ignore_base = false

[docker_context]
symbol = "ïŒˆ"
style = "fg:crust bg:sapphire"
format = "[[ $symbol($context) ](fg:crust bg:sapphire)]($style)"

[helm]
symbol = "îŸ»"
style = "fg:crust bg:sapphire"
format = "[[ $symbol$version ](fg:crust bg:sapphire)]($style)"

[kubernetes]
symbol = "î "
style = "fg:crust bg:sapphire"
format = "[[ $symbol($context) ](fg:crust bg:sapphire)]($style)"

[package]
disabled = false
style = "fg:crust bg:sapphire"
format = "[[ $symbol$version ](fg:crust bg:sapphire)]($style)"
display_private = true

[terraform]
symbol = "î¢½"
style = "fg:crust bg:sapphire"
format = "[[ $symbol$version ](fg:crust bg:sapphire)]($style)"



# --- Timing Modules ---

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:lavender"
format = "[[ ïº $time ](fg:crust bg:lavender)]($style)"

# Output the command duration
[cmd_duration]
disabled = false
show_milliseconds = true
style = "fg:crust bg:lavender"
format = "[[ ó±« $duration ](fg:crust bg:lavender)]($style)"
show_notifications = false

# Customize the battery indicator
[battery]
format = "[$symbol $percentage]($style) "
empty_symbol = "ğŸª«"
charging_symbol = "ğŸ”‹"
full_symbol = "ğŸ”‹"

[[battery.display]]
threshold = 10
style = "red"



# --- Disabled Modules ---

[aws]
disabled = true

[azure]
disabled = true

[buf]
disabled = true

[container]
disabled = true

[daml]
disabled = true

[direnv]
disabled = true

[fossil_branch]
disabled = true

[fossil_metrics]
disabled = true

[gcloud]
disabled = true

[guix_shell]
disabled = true

[meson]
disabled = true

[hg_branch]
disabled = true

[mojo]
disabled = true

[nats]
disabled = true

[netns]
disabled = true

[nix_shell]
disabled = true

[opa]
disabled = true

[openstack]
disabled = true

[pijul_channel]
disabled = true

[pulumi]
disabled = true

[singularity]
disabled = true

[solidity]
disabled = true

[spack]
disabled = true

[vagrant]
disabled = true



# --- Prompt Character ---

[character]
disabled = false
success_symbol = "[â¯](bold fg:green)"
error_symbol = "[â¯](bold fg:red)"
vimcmd_symbol = "[â®](bold fg:green)"
vimcmd_replace_one_symbol = "[â®](bold fg:lavender)"
vimcmd_replace_symbol = "[â®](bold fg:lavender)"
vimcmd_visual_symbol = "[â®](bold fg:yellow)"



# --- Color Palettes ---

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
